name: Docker Image Build and Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md" # 仅修改README.md不触发镜像构建
  workflow_dispatch:  # 支持手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-24.04  # 使用与 VPS 相同的 Ubuntu 版本
    steps:
      - name: Check out GitHub Action
        uses: actions/checkout@v4  
          
      - name: Create simple version file
        run: |
          echo "latest" > VERSION # 将项目版本号静态命名为'latest'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  

      - name: Login to Docker Hub
        uses: docker/login-action@v3  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5  
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/one-hub:latest
          no-cache: true